[package]
name = "whyos_shell"
version = "0.1.1"
edition = "2024"
authors = ["gdziewon"]
description = "A diagnostic shell for the WhyOS RTOS"
license = "MIT OR Apache-2.0"
repository = "https://github.com/gdziewon/whyos"
keywords = ["rtos", "shell", "embedded", "no_std", "diagnostic"]
categories = ["no-std", "embedded", "command-line-interface"]

[dependencies]
whyos = { path = "../whyos", version = "0.1.0" }

embedded-io = "0.7.1"
heapless = "0.9.2" # for String

[features]
docsrs = ["whyos/rp235x"] # workaround to trick docs.rs

[package.metadata.docs.rs]
default-target = "thumbv8m.main-none-eabihf"
features = ["docsrs"]