[package]
name = "whyos"
version = "0.1.1"
edition = "2024"
authors = ["gdziewon"]
description = "A lightweight, preemptive RTOS"
license = "MIT OR Apache-2.0"
repository = "https://github.com/gdziewon/whyos"
keywords = ["rtos", "kernel", "embedded", "no_std", "microcontroller"]
categories = ["no-std", "embedded", "os"]

[package.metadata.docs.rs]
default-target = "thumbv8m.main-none-eabihf"
features = ["rp235x", "task-panic-recovery", "software-watchdog", "defmt"]

[features]
default = []
rp235x = []
task-panic-recovery = []
software-watchdog = []
profiler = []

[dependencies]
critical-section = "1.2"
defmt = { version = "1.0", optional = true }

[target.'cfg(target_arch = "arm")'.dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"

[target.'cfg(target_arch = "riscv32")'.dependencies]
riscv = "0.11"
riscv-rt = "0.12"
