[alias]


build-arm = "build --release --target=thumbv8m.main-none-eabihf"
build-riscv = "build --release --target=riscv32imac-unknown-none-elf"

run-arm = "run --release --target=thumbv8m.main-none-eabihf"
run-riscv = "run --release --target=riscv32imac-unknown-none-elf"

picotool-arm = [
    "run",
    "--release",
    "--target=thumbv8m.main-none-eabihf",
    "--config", "picotool load -u -v -x -t elf'"
]

[build]
target = "thumbv8m.main-none-eabihf"

[target.thumbv8m.main-none-eabihf]
rustflags = [
  "-C", "link-arg=--nmagic", # turns off page alignment of section (saves flash space)
  "-C", "link-arg=-Tlink.x", # use link.x as linker script (cortex-m-rt)
  "-C", "link-arg=-Tdefmt.x", # use defmt.x linker script also (dfmt_rtt)
  "-C", "target-cpu=cortex-m33",
]
runner = "probe-rs run --chip RP235x --no-catch-hardfault --no-catch-reset --disable-progressbars"

[target.riscv32imac-unknown-none-elf]
rustflags = [
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tdefmt.x",
]
runner = "picotool load -u -v -x -t elf"

[env]
DEFMT_LOG = "trace" # enable all log levels